[package]
name = "tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.119"
serde = {version = "1.0.203", features = ["derive"]}
libc = "0.2.155"